### ISSUE TITLE
No such file or directory: 'inputs/graph/track.graph'

### ISSUE THREAD

**Issue by colorblank** [shuangjiexu/MHP-VOS#3]
When run `python test_mht.py `, I got this error at last:

```
Traceback (most recent call last):
  File "test_mht.py", line 123, in <module>
    main()
  File "test_mht.py", line 90, in main
    roi_numbers = mht.iterTracking()
  File "/home/zhangyu/Projects/MHP-VOS/mht/libs/mht.py", line 110, in iterTracking
    paths, best_solution = self.treeToGraph(i+1, treeId)
  File "/home/zhangyu/Projects/MHP-VOS/mht/libs/mht.py", line 307, in treeToGraph
    self.mwis.write_graph(str_list, str_weights)
  File "/home/zhangyu/Projects/MHP-VOS/mht/libs/mwis.py", line 36, in write_graph
    with open(self.graph_file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'inputs/graph/track.graph'
```
Is this graph generated from code or an offline file?
If it is generated from code, what should I do first?

Thnank you!

**Comment by liudaizong** [comment]
> When run `python test_mht.py `, I got this error at last:
> 
> ```
> Traceback (most recent call last):
>   File "test_mht.py", line 123, in <module>
>     main()
>   File "test_mht.py", line 90, in main
>     roi_numbers = mht.iterTracking()
>   File "/home/zhangyu/Projects/MHP-VOS/mht/libs/mht.py", line 110, in iterTracking
>     paths, best_solution = self.treeToGraph(i+1, treeId)
>   File "/home/zhangyu/Projects/MHP-VOS/mht/libs/mht.py", line 307, in treeToGraph
>     self.mwis.write_graph(str_list, str_weights)
>   File "/home/zhangyu/Projects/MHP-VOS/mht/libs/mwis.py", line 36, in write_graph
>     with open(self.graph_file, 'w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'inputs/graph/track.graph'
> ```
> 
> Is this graph generated from code or an offline file?
> If it is generated from code, what should I do first?
> 
> Thnank you!

**Comment by liudaizong** [comment]
> When run `python test_mht.py `, I got this error at last:
> 
> ```
> Traceback (most recent call last):
>   File "test_mht.py", line 123, in <module>
>     main()
>   File "test_mht.py", line 90, in main
>     roi_numbers = mht.iterTracking()
>   File "/home/zhangyu/Projects/MHP-VOS/mht/libs/mht.py", line 110, in iterTracking
>     paths, best_solution = self.treeToGraph(i+1, treeId)
>   File "/home/zhangyu/Projects/MHP-VOS/mht/libs/mht.py", line 307, in treeToGraph
>     self.mwis.write_graph(str_list, str_weights)
>   File "/home/zhangyu/Projects/MHP-VOS/mht/libs/mwis.py", line 36, in write_graph
>     with open(self.graph_file, 'w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'inputs/graph/track.graph'
> ```
> 
> Is this graph generated from code or an offline file?
> If it is generated from code, what should I do first?
> 
> Thnank you!

You can mkdir the folder inputs/graph under the folder mht
